---
azure-aks:
  pipeline:
    Terraform:
      - name: "Azure Subscription ID"
        description: "Azure subscription ID to use for Terraform."
        key: azure_subscription_id
        widget: cy_cred
        type: string
        default: "((azure_admin.subscription_id))"
      - name: "Azure Tenant ID"
        description: "Azure Tenant ID to use for Terraform."
        key: azure_tenant_id
        widget: cy_cred
        type: string
        default: "((azure_admin.tenant_id))"
      - name: "Azure Client ID"
        description: "Azure Client ID to use for Terraform."
        key: azure_client_id
        widget: cy_cred
        type: string
        default: "((azure_admin.client_id))"
      - name: "Azure Client Secret"
        description: "Azure Client Secret to use for Terraform."
        key: azure_client_secret
        widget: cy_cred
        type: string
        default: "((azure_admin.client_secret))"
      - name: "Azure Location"
        description: "Azure location to use for Terraform."
        key: azure_location
        widget: auto_complete
        type: string
        values: ["North Europe","West Europe","France Central","France South"]
        default: "West Europe"
      - name: "Azure Resource Group of the Storage Account"
        description: "Azure Resource Group of the Storage Account to use to store terraform remote state file."
        key: terraform_resource_group_name
        widget: simple_text
        type: string
        default: ($ organization_canonical $)-terraform
      - name: "Azure Storage Account name"
        description: "Azure Storage Account name to use to store terraform remote state file."
        key: terraform_storage_account_name
        widget: cy_cred
        type: string
        default: ((azure_storage_aks.account_name))
      - name: "Azure Storage Account key"
        description: "Azure Storage Account key to use to store terraform remote state file."
        key: terraform_storage_access_key
        widget: cy_cred
        type: string
        default: ((azure_storage_aks.access_key))
      - name: "Azure Storage container name"
        description: "Azure Storage container name to store terraform remote state file."
        key: terraform_storage_container_name
        widget: simple_text
        type: string
        default: ($ organization_canonical $)
      - name: "Azure Storage container path"
        description: "Azure Storage container path to store terraform remote state file."
        key: terraform_storage_container_path
        widget: simple_text
        type: string
        default: ($ project $)/($ environment $)
      - name: "Client ID for the Service Principal"
        description: "Client ID for the Service Principal used by the AKS cluster"
        key: aks_service_principal_client_id
        widget: cy_cred
        type: string
        default: ((custom_($ project $)-($ environment $)-sp.client_id))
      - name: "Client Secret for the Service Principal"
        description: "Client Secret for the Service Principal used by the AKS cluster."
        key: aks_service_principal_client_secret
        widget: cy_cred
        type: string
        default: ((custom_($ project $)-($ environment $)-sp.client_secret))



    Repos:
      - name: "Config repository"
        description: "Git repository URL containing the config of the stack."
        key: config_git_repository
        type: string
        widget: cy_crs
        default: "git@github.com:MyUser/config-aks.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        widget: cy_cred
        default: "((ssh_config.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: config_git_branch
        widget: cy_branch
        type: string
        source: config_git_repository
        default: "master"
        required: true

  terraform:
    config:
      - name: "Resource Group Name"
        description: "Resource Group Name to use for the AKS Cluster"
        key: module.config.resource_group_name
        widget: simple_text
        type: string
        default: "($ project $)-($ environment $)-aks"
      - name: "Cluster name"
        description: "AKS Cluster name"
        key: module.config.cluster_name
        widget: simple_text
        type: string
        default: "($ project $)-($ environment $)"

    vpc:
      - name: "Address Space"
        description: "The virtual network address space."
        key: module.vpc.address_space
        widget: simple_text
        type: string
        default: "10.8.0.0/14"
      - name: "Private subnets"
        description: "The private subnets cidr for the VPC."
        key: module.vpc.subnets
        widget: text_area
        type: map
        default:
          "nodes": "10.8.0.0/16"
          "pods": "10.9.0.0/16"
          "loadbalancers": "10.11.0.0/16"
        # type: raw
        # default: |+
        #   "{ "nodes" = "10.8.0.0/16", "pods"  = "10.9.0.0/16", "loadbalancers" = "10.11.0.0/16",}"

    aks:
      - name: "AKS cluster network plugin"
        description: "AKS cluster network plugin to use, can be either `azure` or `kubenet`."
        key: module.aks.network_plugin
        widget: auto_complete
        type: string
        default: "azure"
        values:
            - "azure"
            - "kubenet"
      - name: "AKS cluster pod CIDR to use"
        description: "AKS cluster pod CIDR to use, required if `network_plugin = kubenet`."
        key: module.aks.network_pod_cidr
        widget: text_area
        type: string
        default: "10.9.0.0/16"
      - name: "AKS cluster pod CIDR to use"
        description: "AKS cluster service CIDR to use, required if `network_plugin = azure`."
        key: module.aks.network_service_cidr
        widget: text_area
        type: string
        default: "10.10.0.0/16"
      - name: "AKS node name"
        description: "AKS default nodes pool given name."
        key: module.aks.node_pool_name
        widget: simple_text
        type: string
        default: "default"
      - name: "Node size"
        description: "AKS default nodes virtualmachine size."
        key: module.aks.node_size
        widget: simple_text
        type: string
        default: "Standard_DS2_v2"
      - name: "Node desired number"
        description: "AKS default nodes desired count."
        key: module.aks.node_count
        widget: simple_text
        type: string
        default: "1"
        required: true

gcp-gke:
  pipeline:
    Terraform:
      - name: "GCP json credentials"
        description: "GCP JSON for Terraform. See value format [here](https://docs.cycloid.io/advanced-guide/integrate-and-use-cycloid-credentials-manager.html#vault-in-the-pipeline)"
        key: gcp_credentials_json
        widget: cy_cred
        type: string
        default: "((gcp.json_key))"
      - name: "GCP Project"
        description: "Google Cloud Platform project to use for Terraform."
        key: gcp_project
        widget: simple_text
        type: string
        default: ($ organization_canonical $)
      - name: "GCP region"
        description: "Google Cloud Platform region to use for Terraform."
        key: gcp_region
        widget: auto_complete
        type: string
        values: ["europe-west1","europe-west2","europe-west3","europe-west4","europe-north1","europe-central2"]
        default: europe-west1
      - name: "Terraform storage bucket"
        description: "Google Cloud Storage bucket name to store terraform remote state file."
        key: terraform_storage_bucket_name
        widget: simple_text
        type: string
        default: ($ organization_canonical $)-terraform-remote-state

    Repos:
      - name: "Config repository"
        key: config_git_repository
        type: string
        widget: cy_crs
        description: "Git repository URL containing the config of the stack."
        default: "git@github.com:MyUser/config-gke.git"
        required: true
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        widget: cy_cred
        default: "((ssh_config.ssh_key))"
        required: true
      - name: "Config branch"
        description: "Branch of the config Git repository."
        key: config_git_branch
        widget: cy_branch
        type: string
        source: config_git_repository
        default: "master"
        required: true

  terraform:
    config:
      - name: "Cluster name"
        description: "GKE Cluster Name."
        key: module.config.cluster_name
        widget: simple_text
        type: string
        default: "($ project $)-($ environment $)"

    vpc:
      - name: "VPC subnet CIDR"
        description: "The CIDR of the VPC subnet."
        key: module.vpc.subnet_cidr
        widget: simple_text
        type: string
        default: "10.8.0.0/16"
      - name: "Pods secondary range CIDR"
        description: "The CIDR of the pods secondary range."
        key: module.vpc.pods_cidr
        widget: simple_text
        type: string
        default: "10.9.0.0/16"
      - name: "Services secondary range CIDR"
        description: "The CIDR of the services secondary range."
        key: module.vpc.services_cidr
        widget: simple_text
        type: string
        default: "10.10.0.0/16"

    gke:
      - name: "Node Pools"
        description: "GKE Cluster list of maps containing node pools to create."
        key: module.gke.node_pools
        widget: text_area
        type: raw
        default: |+
          "[
            {
              name         = "my-node-pool"
              machine_type = "n1-standard-1"
              image_type   = "COS"
              auto_repair  = true
              auto_upgrade = false
              preemptible  = false
              autoscaling        = true
              initial_node_count = 1
              min_count          = 1
              max_count          = 1
              local_ssd_count = 0
              disk_size_gb    = 100
              disk_type       = "pd-ssd"
            },
          ]"

scaleway-kapsule:
  pipeline:
    Terraform:
      - name: "Scaleway project id"
        description: "Scaleway project id where to create resources."
        key: scw_project_id
        widget: simple_text
        type: string
        required: true
      - name: "Scaleway access key"
        description: "Scaleway access key for Terraform."
        key: scw_access_key
        widget: cy_cred
        type: string
        default: "((scaleway.access_key))"
      - name: "Scaleway secret key"
        description: "Scaleway access key for Terraform."
        key: scw_secret_key
        widget: cy_cred
        type: string
        default: "((scaleway.secret_key))"
      - name: "Scaleway organization ID"
        description: "Scaleway organization ID for Terraform."
        key: scw_organization_id
        widget: cy_cred
        type: string
        default: "((scaleway.organization_id))"
      - name: "Scaleway region"
        description: Scaleway region to use for Terraform."
        key: scw_default_region
        widget: auto_complete
        type: string
        values: ["fr-par","nl-ams","pl-waw"]
        default: fr-par
      - name: "Terraform storage bucket"
        description: "Object Storage Bucket name to store terraform remote state file."
        key: terraform_storage_bucket_name
        widget: simple_text
        type: string
        default: ($ organization_canonical $)-terraform-remote-state

  terraform:
    config:
      - name: "Cluster name"
        description: "Kapsule Cluster Name."
        key: module.config.cluster_name
        widget: simple_text
        type: string
        default: "($ project $)-($ environment $)"

    kapsule:
      - name: "Cluster version"
        description: "Kapsule cluster version."
        key: module.kapsule.cluster_version
        widget: simple_text
        type: string
        default: "1.27"
      - name: "Container Network Interface"
        description: "The Container Network Interface (CNI) for the Kubernetes cluster"
        key: module.kapsule.cni
        widget: auto_complete
        type: string
        default: "cilium"
        values:
            - "cilium"
            - "calico"
            - "weave"
            - "flannel"
      - name: "Kubernetes auto upgrade"
        description: "Set to `true` to enable Kubernetes patch version auto upgrades."
        key: module.kapsule.auto_upgrade
        widget: switch
        type: boolean
        default: true
      - name: "Maintenance window day"
        description: "The day of the auto upgrade maintenance window"
        key: module.kapsule.maintenance_window_day
        widget: auto_complete
        type: string
        default: "tuesday"
        values:
            - "any"
            - "monday"
            - "tuesday"
            - "wednesday"
            - "thursday"
            - "friday"
            - "saturday"
            - "sunday"
      - name: "Maintenance window start hour"
        description: "The start hour (UTC) of the 2-hour auto upgrade maintenance window (`0` to `23`)."
        key: module.kapsule.maintenance_window_start_hour
        widget: slider_range
        type: integer
        default: 5
        values:
            - 0
            - 23

    node-pool:
      - name: "Node pool name"
        description: "Kapsule node group given name."
        key: module.node_pool.node_pool_name
        widget: simple_text
        type: string
        default: "standard"
      - name: "Node type"
        description: "Type of instance to use for node servers."
        key: module.node_pool.node_type
        widget: auto_complete
        type: string
        default: "GP1-XS"
        required: true
        values:
            - "GP1-XS"
            - "GP1-S"
            - "GP1-M"
            - "GP1-L"
            - "GP1-XL"
      - name: "Node desired number"
        description: "Desired number of node servers."
        key: module.node_pool.node_count
        widget: number
        type: integer
        default: 1
        required: true
      - name: "Enable auto scaling"
        description: "Enables the autoscaling feature for this pool."
        key: module.node_pool.enable_autoscaling
        widget: switch
        type: boolean
        default: false
      - name: "Minimum pool size"
        description: "The minimum size of the pool, used by the autoscaling feature."
        key: module.node_pool.node_autoscaling_min_size
        widget: number
        type: integer
        default: 1
      - name: "Maximum pool sizer"
        description: " The maximum size of the pool, used by the autoscaling feature."
        key: module.node_pool.node_autoscaling_max_size
        widget: number
        type: integer
        default: 10
      - name: "Enable auto healing"
        description: "Enables the autohealing feature for this pool."
        key: module.node_pool.enable_autohealing
        widget: switch
        type: boolean
        default: true
      - name: "Placement group ID"
        description: "The placement group the nodes of the pool will be attached to."
        key: module.node_pool.placement_group_id
        widget: simple_text
        type: string
        default: ""
      - name: "Extra tags"
        description: "Dict of extra tags to add on the pool."
        key: module.node_pool.extra_tags
        widget: text_area
        type: raw
        default: "[]"

scaleway-nodes:
  pipeline:
    Terraform:
      - name: "Scaleway access key"
        description: "Scaleway access key for Terraform."
        key: scw_access_key
        widget: cy_cred
        type: string
        default: "((scaleway.access_key))"
      - name: "Scaleway secret key"
        description: "Scaleway access key for Terraform."
        key: scw_secret_key
        widget: cy_cred
        type: string
        default: "((scaleway.secret_key))"
      - name: "Scaleway organization ID"
        description: "Scaleway organization ID for Terraform."
        key: scw_organization_id
        widget: cy_cred
        type: string
        default: "((scaleway.organization_id))"
      - name: "Scaleway region"
        description: Scaleway region to use for Terraform."
        key: scw_default_region
        widget: auto_complete
        type: string
        values: ["fr-par","nl-ams","pl-waw"]
        default: fr-par
      - name: "Terraform storage bucket"
        description: "Object Storage Bucket name to store terraform remote state file."
        key: terraform_storage_bucket_name
        widget: simple_text
        type: string
        default: ($ organization_canonical $)-terraform-remote-state

  terraform:
    config:
      - name: "Cluster name"
        description: "Kapsule Cluster Name."
        key: module.config.cluster_name
        widget: simple_text
        type: string
        default: "($ project $)-($ environment $)"

    node-pool:
      - name: "Kubernetes cluster id"
        description: "The Kubernetes id the nodes of the pool will be attached to."
        key: module.node_pool.cluster_id
        widget: simple_text
        type: string
        default: "data.terraform_remote_state.kubernetes-infra.outputs.cluster_id"
      - name: "Node pool name"
        description: "Kapsule node group given name."
        key: module.node_pool.node_pool_name
        widget: simple_text
        type: string
        default: "standard"
      - name: "Node type"
        description: "Type of instance to use for node servers."
        key: module.node_pool.node_type
        widget: auto_complete
        type: string
        default: "GP1-XS"
        required: true
        values:
            - "GP1-XS"
            - "GP1-S"
            - "GP1-M"
            - "GP1-L"
            - "GP1-XL"
      - name: "Node desired number"
        description: "Desired number of node servers."
        key: module.node_pool.node_count
        widget: number
        type: integer
        default: 1
        required: true
      - name: "Enable auto scaling"
        description: "Enables the autoscaling feature for this pool."
        key: module.node_pool.enable_autoscaling
        widget: switch
        type: boolean
        default: false
      - name: "Minimum pool size"
        description: "The minimum size of the pool, used by the autoscaling feature."
        key: module.node_pool.node_autoscaling_min_size
        widget: number
        type: integer
        default: 1
      - name: "Maximum pool sizer"
        description: " The maximum size of the pool, used by the autoscaling feature."
        key: module.node_pool.node_autoscaling_max_size
        widget: number
        type: integer
        default: 10
      - name: "Enable auto healing"
        description: "Enables the autohealing feature for this pool."
        key: module.node_pool.enable_autohealing
        widget: switch
        type: boolean
        default: true
      - name: "Placement group ID"
        description: "The placement group the nodes of the pool will be attached to."
        key: module.node_pool.placement_group_id
        widget: simple_text
        type: string
        default: ""
      - name: "Extra tags"
        description: "Dict of extra tags to add on the pool."
        key: module.node_pool.extra_tags
        widget: text_area
        type: raw
        default: "[]"
